### ISSUE TITLE
Is there a standard implementation of Site.features? 

### ISSUE THREAD

**Issue by spapas** [caltechads/wagtail-jetstream#3]
I see that this project contains various references to "features" like a feature_registry or Site.features etc. Is there an implementation / API that is used for that ? TY

**Comment by cnk** [comment]
Sorry, features, feature_registry, and Site.features is from one of our packages that is not open-sourced. 

My recommendation is that you fork this repository and remove the @register_feature decorators and FeatureCustomizedStreamBlock replacing all mentions of FeatureCustomizedStreamBlock with Wagtail's StreamBlock. That will remove the dependency on our djunk package AND on our non-open-source features registry.

The point of FeatureCustomizedStreamBlock is to allow us to include some blocks on some but not all sites in a multi-tenanted install. Unless you have that specific use case, FeatureCustomizedStreamBlock is just overhead you don't want.

**Comment by spapas** [comment]
Makes sense thank you. Would it be possible to provide a couple of examples of features that you use on some sites but not others so I can understand better if that's something I'd like to implement or not ?

**Comment by cnk** [comment]
We have sometimes used feature flags to pre-release a feature we want to show off but is not quite ready for general use. But the majority of features we use this to control are embed blocks - iframes and WuFoo or JotForm embeds - that we want people to tell us they are using before allowing it. Now that we use [CFPB's wagtail-inventory](https://github.com/cfpb/wagtail-inventory) package, having up front control is less important since we can find sites/pages using specific blocks to do a manual check for appropriateness.

**Comment by spapas** [comment]
Very nice, thank you!
